language: node_js

node_js: 6

env:
  - NG_VERSION=4 TS_VERSION=2.3.4
  - NG_VERSION=5 TS_VERSION=2.4.2
  - NG_VERSION=6 TS_VERSION=2.7.2

install:
  - npm install typescript@${TS_VERSION}
  - npm install @angular/common@${NG_VERSION} @angular/core@${NG_VERSION} @angular/forms@${NG_VERSION}
  - npm install @angular/platform-browser@${NG_VERSION} @angular/platform-browser-dynamic@${NG_VERSION}
  - npm install @angular/compiler@${NG_VERSION} @angular/compiler-cli@${NG_VERSION}
  - npm install

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
